#
# codemagic.yaml - مصحح مع استخدام working_directory
#

workflows:
  android-release:
    name: Android Release Build
    
    environment:
      java: 11 # ⬅️ تم تصحيح البنية
      groups:
        - firebase_credentials 
        # - keystore_credentials 
    
    scripts:
      
      # 1. فك تشفير google-services.json
      # هذه الخطوة تبقى كما هي، لكن يجب التأكد من المسار النهائي
      - name: Decode google-services.json
        script: |
          if [ -n "$GOOGLE_SERVICES_JSON" ]; then
            echo "Decoding google-services.json..."
            # المسار: app/google-services.json (بافتراض أن app/ هو مجلد في الجذر)
            echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json
            echo "google-services.json created in app/ directory."
          else
            echo "GOOGLE_SERVICES_JSON environment variable not found. Skipping file creation."
          fi
          
      # 2. منح إذن التنفيذ لـ gradlew
      - name: Grant execute permission for gradlew
        script: |
          # ⬅️ استخدام ./gradlew لكي يتم العثور على الملف في أي working_directory
          chmod +x ./gradlew 
        working_directory: android # ⬅️ يتم تنفيذ الأمر داخل مجلد "android"

      # 3. تشغيل عملية البناء
      - name: Build Android Release AAB
        script: |
          # ⬅️ استخدام ./gradlew لكي يتم العثور على الملف
          ./gradlew bundleRelease 
        working_directory: android # ⬅️ يتم تنفيذ الأمر داخل مجلد "android"
          
    # 4. القطع الأثرية (Artifacts)
    artifacts:
      # يجب أن تعكس مسارات القطع الأثرية وجود مجلد android/app/
      - android/app/build/outputs/bundle/release/*.aab
      - android/app/build/outputs/apk/release/*.apk
