#
# codemagic.yaml - مصحح ليناسب بنية Codemagic
#

workflows:
  android-release:
    name: Android Release Build
    
    # 1. البيئة (Environment Setup)
    environment:
      # يتم وضع إعدادات Java و Docker في هذا المستوى 
      # ملاحظة: يتم تحديد صورة Docker في إعدادات التطبيق أو عبر خاصية 'instance_type' إذا لزم الأمر
      # يتم تحديد إصدار Java المطلوب
      java: 
        - 11
        
      # مجموعة المتغيرات السرية (يجب تعريفها في إعدادات Codemagic)
      groups:
        - firebase_credentials # يحتوي على GOOGLE_SERVICES_JSON
        # - keystore_credentials # يمكن إضافتها لاحقاً لتوقيع التطبيق
    
    # 2. خطوة التفعيل (Checkout) - يتم تفعيلها تلقائياً
    
    # 3. خطوات البناء (Scripts)
    scripts:
      
      # 3.1. منح إذن التنفيذ لـ gradlew
      - name: Grant execute permission for gradlew
        script: |
          # بما أن ملف gradlew في جذر المستودع
          chmod +x gradlew
          
      # 3.2. توفير ملف google-services.json
      - name: Decode google-services.json
        # **الحل لـ Error 2 & 3:**
        # تم دمج المنطق الشرطي (if) مع الأمر script نفسه لأن Codemagic لا يدعم 'if' مباشرة تحت 'script'
        script: |
          # التحقق مما إذا كان المتغير GOOGLE_SERVICES_JSON موجوداً، ثم تنفيذ فك التشفير
          if [ -n "$GOOGLE_SERVICES_JSON" ]; then
            echo "Decoding google-services.json..."
            echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json
            echo "google-services.json created in app/ directory."
          else
            echo "GOOGLE_SERVICES_JSON environment variable not found. Skipping file creation."
          fi
          
      # 3.3. تشغيل عملية البناء
      - name: Build Android Release APK
        script: |
          # لتوليد APK (هذا هو الأمر الأساسي للبناء)
          ./gradlew assembleRelease
          
          # لتوليد حزمة AAB (موصى بها لمتجر Play):
          # ./gradlew bundleRelease
          
    # 4. القطع الأثرية (Artifacts)
    artifacts:
      - app/build/outputs/apk/release/*.apk 
      - app/build/outputs/bundle/release/*.aab
